name: Step 1 - Awaken The Codespace

on:
  repository_dispatch:
    types: [codespace-awakened]

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_2_FILE: ".github/steps/2-summon-first-oracle.md"

jobs:
  find-workshop-issue:
    name: Find the workshop issue
    uses: lufomatics/reusable-workshops/.github/workflows/find-workshop-issue.yaml@v1.0.0
    with:
      issue-title-text: "Workshop"

  acknowledge-awakening:
    name: Confirm codespace awakening
    runs-on: ubuntu-latest
    needs: [find-workshop-issue]
    if: |
      !github.event.repository.is_template

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update workshop status in README
        run: |
          python - <<'PY'
          from pathlib import Path

          status = "🚀 Sinal do Codespace recebido! Converse com o primeiro oráculo diretamente pela issue."
          path = Path('README.md')
          text = path.read_text()
          start = '<!--WORKSHOP_STATUS-->'
          end = '<!--END_WORKSHOP_STATUS-->'
          if start not in text or end not in text:
              raise SystemExit('Workshop status markers not found in README.md')
          prefix, _, rest = text.partition(start)
          _, _, suffix = rest.partition(end)
          path.write_text(f"{prefix}{start}{status}{end}{suffix}")
          PY

      - name: Commit status update
        uses: EndBug/add-and-commit@v9
        continue-on-error: true
        with:
          add: README.md
          message: "workshop status: oraculo inicial liberado"
          default_author: github_actions
          pull: --rebase --autostash

      - name: Post awakening confirmation comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ needs.find-workshop-issue.outputs.issue-url }}
          CODESPACE_NAME: ${{ github.event.client_payload.codespace }}
        run: |
          codespace_name="${CODESPACE_NAME:-um codespace sem nome}"
          gh issue comment "$ISSUE_URL" \
            --body "O Codespace **${codespace_name}** enviou o sinal de despertar. Vamos consultar o primeiro oráculo!"

      - name: Post instructions for next step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ needs.find-workshop-issue.outputs.issue-url }}
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$STEP_2_FILE"

      - name: Update button in README
        run: |
          # Change button from "Start Workshop" to "Continue Workshop"
          target=Start_Workshop-008000
          replacement=Continue_Workshop-008000
          sed -i "s|$target|$replacement|g" README.md

      - name: Disable this workflow and enable the next one
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow enable "Step 2 - Summon Your First Oracle"
          gh workflow disable "Step 1 - Awaken The Codespace"
